// <auto-generated />
using System;
using EmolyeePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmolyeePortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908064208_Mig1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmolyeePortal.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EmolyeePortal.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "NetWork  Engineer"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "HR Specialist"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "HR Manager"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "Talent Acquisition Coordinator"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Sales Executive "
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Sales Manager "
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Account Executive "
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Office Manager "
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Executive Assistence "
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Receptionist "
                        });
                });

            modelBuilder.Entity("EmolyeePortal.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 1,
                            Email = "John@example.com",
                            EmployeeTypeId = 1,
                            FullName = "John Snow",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 3,
                            Email = "Patrik@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Patrik BedDavid",
                            Gender = "Female",
                            HireDate = new DateTime(2018, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1991, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 5,
                            Email = "Shamil@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Shamil",
                            Gender = "Male",
                            HireDate = new DateTime(2019, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 61000m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1993, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 8,
                            Email = "Chris@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Chris Willx",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 30000m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1982, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 9,
                            Email = "Hamza@example.com",
                            EmployeeTypeId = 2,
                            FullName = "Hamza Ahmed",
                            Gender = "Female",
                            HireDate = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 67000m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1984, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 10,
                            Email = "Iman@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Iman Gadzi",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 63000m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1993, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 12,
                            Email = "David@example.com",
                            EmployeeTypeId = 2,
                            FullName = "David Goggins",
                            Gender = "Female",
                            HireDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1994, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 9,
                            Email = "Andrew@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Adrew T",
                            Gender = "Male",
                            HireDate = new DateTime(2018, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1996, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 7,
                            Email = "Tristan@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Tristan T",
                            Gender = "Female",
                            HireDate = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1988, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 4,
                            Email = "Luke@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Luke Balmer",
                            Gender = "Male",
                            HireDate = new DateTime(2022, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1987, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 6,
                            Email = "khabib@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Khabib NM",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1995, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 5,
                            Email = "Jones@example.com",
                            EmployeeTypeId = 2,
                            FullName = "John Jones",
                            Gender = "Female",
                            HireDate = new DateTime(2019, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 74000m
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1997, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 2,
                            Email = "Mike@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Mike Tyson",
                            Gender = "Male",
                            HireDate = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 79000m
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1989, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 9,
                            Email = "Bruce@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Bruce Wayne",
                            Gender = "Female",
                            HireDate = new DateTime(2017, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1992, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 4,
                            Email = "Batman@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Batman",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 62000m
                        });
                });

            modelBuilder.Entity("EmolyeePortal.Models.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "Permanent"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Temporary"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Intern"
                        });
                });

            modelBuilder.Entity("EmolyeePortal.Models.Designation", b =>
                {
                    b.HasOne("EmolyeePortal.Models.Department", "Department")
                        .WithMany("Designations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmolyeePortal.Models.Employee", b =>
                {
                    b.HasOne("EmolyeePortal.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmolyeePortal.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmolyeePortal.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("EmolyeePortal.Models.Department", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmolyeePortal.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
